name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - uses: actions/checkout@v4
    - run: curl -sSL https://install.python-poetry.org | python -
    - run: poetry install
    - run: poetry run python download_lib.py
    - run: poetry run python build_ffi.py
    - run: poetry run pytest